name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with your required Python version

    - name: Install dependencies
      run: |
        pip install pyinstaller winshell pywin32
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller DontForgetToSave.spec

    - name: Download Inno Setup
      run: curl -Lo isetup.exe https://jrsoftware.org/download.php/is.exe

    - name: Install Inno Setup
      shell: pwsh
      run: Start-Process -FilePath ./isetup.exe -ArgumentList '/silent', '/dir="C:\Program Files (x86)\Inno Setup 6"' -NoNewWindow -Wait

    - name: Run Inno Setup
      shell: pwsh
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: DontForgetToSave_installer
        path: ./DontForgetToSave_installer.exe
